version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins-master 
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTIONS="-Xmx1024m"
      - JENKINS_OPTIONS=" --handlerCountMax=300" 
